### ISSUE TITLE
Can I use the Agora AgoraRtcEngine_iOS Pod directly

### ISSUE THREAD

**Issue by Jonovono** [syanbo/react-native-agora#59]
Hi. Can I put this in my Podfile instead of installing the pod through node_modules?

I've tried it but I get some errors. Namely

`Use of undeclared identifier 'AgoraConnectionChanged....`

Any ideas? Thanks.

**Comment by Matrixbirds** [comment]
Yes you can, but i think it is bad practice, because you need to confirm which version is the react-native-agora new released dependency. Probably you could provide more details here that I would help you to fix it.

**Comment by Jonovono** [comment]
Cool, thanks @Matrixbirds , looks like I was able to get it on second try :)
